import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Dialog, DialogTitle, DialogContent, DialogActions, Button, Typography, Box, Switch, FormControlLabel, Tooltip, } from '@mui/material';
import InfoIcon from '@mui/icons-material/Info';
import { usePreferences } from '../contexts/PreferencesContext';
export var Settings = function (_a) {
    var open = _a.open, onClose = _a.onClose;
    var _b = usePreferences(), preferences = _b.preferences, updatePreference = _b.updatePreference;
    return (_jsxs(Dialog, { open: open, onClose: onClose, maxWidth: "sm", fullWidth: true, children: [_jsx(DialogTitle, { children: "Settings" }), _jsx(DialogContent, { children: _jsxs(Box, { sx: { mb: 3 }, children: [_jsx(Typography, { variant: "h6", sx: { mb: 2 }, children: "Bookmark Preferences" }), _jsxs(Box, { sx: { display: 'flex', alignItems: 'center', mb: 2 }, children: [_jsx(FormControlLabel, { control: _jsx(Switch, { checked: preferences.autoBookmarkParents, onChange: function (e) { return updatePreference('autoBookmarkParents', e.target.checked); } }), label: "Automatically bookmark parent clauses when bookmarking child clauses" }), _jsx(Tooltip, { title: "When enabled, parent clause bookmarks will be automatically added when their child clauses are bookmarked to ensure no mandatory clauses are missed", children: _jsx(InfoIcon, { fontSize: "small", sx: { ml: 1, color: 'text.secondary' } }) })] }), _jsxs(Box, { sx: { display: 'flex', alignItems: 'center', mb: 2 }, children: [_jsx(FormControlLabel, { control: _jsx(Switch, { checked: preferences.removeParentWithChild === true, onChange: function (e) { return updatePreference('removeParentWithChild', e.target.checked ? true : null); } }), label: "Always remove parent clause when removing child clause" }), _jsx(Tooltip, { title: "When enabled, parent clause bookmarks will be automatically removed when their child clauses are unbookmarked", children: _jsx(InfoIcon, { fontSize: "small", sx: { ml: 1, color: 'text.secondary' } }) })] }), _jsx(Button, { variant: "outlined", color: "primary", onClick: function () { return updatePreference('removeParentWithChild', null); }, sx: { mt: 1 }, children: "Reset to Ask Each Time" })] }) }), _jsx(DialogActions, { children: _jsx(Button, { onClick: onClose, children: "Close" }) })] }));
};
