import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { ReactQueryDevtools } from '@tanstack/react-query-devtools';
import './index.css';
import App from './App';
import { AuthProvider } from './contexts/AuthContext';
import { DEBUG_LOG } from './config/debug';
import { DebugErrorBoundary } from './components/DebugErrorBoundary';
import './utils/setupDebug';
var queryClient = new QueryClient();
createRoot(document.getElementById('root')).render(_jsx(StrictMode, { children: _jsxs(QueryClientProvider, { client: queryClient, children: [_jsx(AuthProvider, { children: DEBUG_LOG ? (_jsx(DebugErrorBoundary, { children: _jsx(App, {}) })) : (_jsx(App, {})) }), import.meta.env.DEV && _jsx(ReactQueryDevtools, { initialIsOpen: false })] }) }));
